services:
  db:
    image: postgres:15
    container_name: mysa_mis_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - odoo-network

  odoo:
    build: .
    container_name: mysa_mis_odoo
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./custom_addons:/mnt/extra-addons
      - ./odoo-docker.conf:/etc/odoo/odoo.conf
    restart: unless-stopped
    networks:
      - odoo-network

networks:
  odoo-network:
    driver: bridge

volumes:
  odoo-db-data:
  odoo-web-data:
