apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/leonmwila/mysa-mis
    newName: ghcr.io/leonmwila/mysa-mis
    newTag: sha-c76095a

patches:
  - path: ingress-patch.yaml
  - path: postgres-secret-patch.yaml
  - path: odoo-config-patch.yaml
  - path: odoo-deployment-patch.yaml
