apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-config
data:
  odoo.conf: |
    [options]
    db_host = postgres
    db_port = 5432
    db_user = odoo
    db_password = Admin@2023
    db_maxconn = 256
    http_port = 8069
    proxy_mode = True
    addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
    log_level = info
    logfile = False
    workers = 6
    max_cron_threads = 2
    list_db = True
    admin_passwd = Admin@2023
    data_dir = /var/lib/odoo
